name: Changelog Automático

on:
  push:
    branches:
      - 'development'
      - 'main'

permissions:
  contents: write

jobs:
  call-changelog-workflow:
    uses: Grupo-Altia/shared-actions/.github/workflows/changelog-reusable.yml@main
    secrets: inherit
